# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    tags: ["release/*"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.

    - name: Install dependencies
      run: |
        go get .

    - name: Build
      run: ./build.sh

#    - name: Test
#      run: go test -v ./...

    - uses: actions/upload-artifact@v4.6.0
      with:
        name: picons-update
        path: dist/

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/release/')
      with:
        files: |
          dist/picons-update-amd64-linux
          dist/picons-update-amd64-darwin
          dist/picons-update-arm
          dist/picons-update.exe
